/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.librarymanagementsystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ohidu
 */
public class RemoveBook extends javax.swing.JFrame {

    /**
     * Creates new form RemoveBook
     */
    public RemoveBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_back = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_bookId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_bookName = new javax.swing.JTextField();
        btn_removeAll = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_quantity = new javax.swing.JTextField();
        btn_remove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(200, 200, 200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_back.setBackground(new java.awt.Color(0, 102, 102));
        btn_back.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("<<Back");
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Enter Book Id: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        txt_bookId.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(txt_bookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 387, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Enter Book Name: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        txt_bookName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(txt_bookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 387, -1));

        btn_removeAll.setBackground(new java.awt.Color(0, 102, 102));
        btn_removeAll.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_removeAll.setForeground(new java.awt.Color(255, 255, 255));
        btn_removeAll.setText("Remove All Copies");
        btn_removeAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_removeAllMouseClicked(evt);
            }
        });
        btn_removeAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeAllActionPerformed(evt);
            }
        });
        jPanel1.add(btn_removeAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Enter quantity: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        txt_quantity.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(txt_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 387, -1));

        btn_remove.setBackground(new java.awt.Color(0, 102, 102));
        btn_remove.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_remove.setForeground(new java.awt.Color(255, 255, 255));
        btn_remove.setText("Remove");
        btn_remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_removeMouseClicked(evt);
            }
        });
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 735, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_removeAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_removeAllActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_removeActionPerformed

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        // TODO add your handling code here:
        AdminHomepage ah = new AdminHomepage();
        ah.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_backMouseClicked

    private void btn_removeAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_removeAllMouseClicked
        // TODO add your handling code here:
        String bookId = txt_bookId.getText();
        String bookName = txt_bookName.getText();
        if(bookId.equals("") && bookName.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter book id or name!");
            return;
        }
        Connection con = DBConnection.getConnection();
        if(!bookId.equals("")){
            try{
                String sq = "delete from books where bookId = ?;";
                PreparedStatement rmb = con.prepareStatement(sq);
                rmb.setString(1, bookId);
                int del = rmb.executeUpdate();
                if(del>0){
                    JOptionPane.showMessageDialog(this, "The book has been removed!");
                    return;
                }
                else{
                    JOptionPane.showMessageDialog(this, "The book could not be removed or "
                            + "it doesn't exist!");
                    return;
                }
            }
            catch(Exception e){
                System.out.println(e);
                return;
            }       
        }
        if(!bookName.equals("")){
            try{
                String sq = "delete from books where bookName = ?;";
                PreparedStatement rmb = con.prepareStatement(sq);
                rmb.setString(1, bookName);
                int del = rmb.executeUpdate();
                if(del>0){
                    JOptionPane.showMessageDialog(this, "The book has been removed!");
                    return;
                }
                else{
                    JOptionPane.showMessageDialog(this, "The book could not be removed or "
                            + "it doesn't exist!");
                    return;
                }
            }
            catch(Exception e){
                System.out.println(e);
                return;
            }
        }
    }//GEN-LAST:event_btn_removeAllMouseClicked

    private void btn_removeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_removeMouseClicked
        // TODO add your handling code here:
        String bookId = txt_bookId.getText();
        String bookName = txt_bookName.getText();
        if(bookId.equals("") && bookName.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter book id or name!");
            return;
        }
        if(txt_quantity.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter quantity to remove!");
            return;
        }
        int quantity = Integer.parseInt(txt_quantity.getText());
        Connection con = DBConnection.getConnection();
        if(!bookId.equals("")){
            try{
                String sqgtb = "select * from books where bookId = ?;";
                PreparedStatement gtb = con.prepareStatement(sqgtb); 
                gtb.setString(1, bookId);
                ResultSet theB = gtb.executeQuery();
                if(theB.next()){
                    int curr_quan = theB.getInt("quantity");
                    int remaining = curr_quan - quantity;
                    if(remaining<0){
                        JOptionPane.showMessageDialog(this, "There are only "+curr_quan+" copies of this book!");
                        return;
                    }
                    else{
                        String squq = "update books set quantity = ? where bookId = ?;";
                        PreparedStatement uq = con.prepareStatement(squq);
                        uq.setInt(1, remaining);
                        uq.setString(2, bookId);
                        int udqd = uq.executeUpdate();
                        if(udqd>0){
                            JOptionPane.showMessageDialog(this, "Removed "+quantity
                                    +" copies of this book successfully!");
                            return;
                        }
                        else{
                            JOptionPane.showMessageDialog(this, "The book could not be removed!");
                        }
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this, "This book doesn't exist!");
                    return;
                }
            }
            catch(Exception e){
                System.out.println(e);
            }
        }
        if(!bookName.equals("")){
            try{
                String sqgtb = "select * from books where bookName = ?;";
                PreparedStatement gtb = con.prepareStatement(sqgtb); 
                gtb.setString(1, bookName);
                ResultSet theB = gtb.executeQuery();
                if(theB.next()){
                    int curr_quan = theB.getInt("quantity");
                    int remaining = curr_quan - quantity;
                    if(remaining<0){
                        JOptionPane.showMessageDialog(this, "There are only "+curr_quan+" copies of this book!");
                        return;
                    }
                    else{
                        String squq = "update books set quantity = ? where bookName = ?;";
                        PreparedStatement uq = con.prepareStatement(squq);
                        uq.setInt(1, remaining);
                        uq.setString(2, bookName);
                        int udqd = uq.executeUpdate();
                        if(udqd>0){
                            JOptionPane.showMessageDialog(this, "Removed "+quantity
                                    +" copies of this book successfully!");
                            return;
                        }
                        else{
                            JOptionPane.showMessageDialog(this, "The book could not be removed!");
                        }
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this, "This book doesn't exist!");
                    return;
                }
            }
            catch(Exception e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_btn_removeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton btn_removeAll;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_bookId;
    private javax.swing.JTextField txt_bookName;
    private javax.swing.JTextField txt_quantity;
    // End of variables declaration//GEN-END:variables
}
